"""users table

Revision ID: 1376cd40b402
Revises: 
Create Date: 2020-05-01 17:42:35.848299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1376cd40b402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direction',
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('Degree_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Degree_id'], ['degree.id'], ),
    sa.ForeignKeyConstraint(['Faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('Direction_id', sa.Integer(), nullable=True),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['Direction_id'], ['direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('FullName', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('Phone', sa.String(length=12), nullable=True),
    sa.Column('access', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_FullName'), 'user', ['FullName'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('form_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('Year', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_all_id'), 'form_all', ['id'], unique=True)
    op.create_index(op.f('ix_form_all_timestamp'), 'form_all', ['timestamp'], unique=False)
    op.create_table('group_stud',
    sa.Column('Profile_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_one',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('NumForm', sa.Integer(), nullable=False),
    sa.Column('Group_id', sa.Integer(), nullable=False),
    sa.Column('Degree_id', sa.Integer(), nullable=True),
    sa.Column('Direction_id', sa.Integer(), nullable=True),
    sa.Column('Direction_name', sa.String(), nullable=True),
    sa.Column('Profile_id', sa.Integer(), nullable=True),
    sa.Column('Profile_name', sa.String(), nullable=True),
    sa.Column('Course', sa.Integer(), nullable=True),
    sa.Column('NumStudents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['NumForm'], ['form_all.id'], ),
    sa.ForeignKeyConstraint(['Profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('NumForm', 'Group_id')
    )
    op.create_index(op.f('ix_form_one_Group_id'), 'form_one', ['Group_id'], unique=True)
    op.create_index(op.f('ix_form_one_timestamp'), 'form_one', ['timestamp'], unique=False)
    op.create_table('form_two',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('NumForm', sa.Integer(), nullable=False),
    sa.Column('Group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FullSubject', sa.String(), nullable=True),
    sa.Column('ВriefSubject', sa.String(), nullable=True),
    sa.Column('LecturerName', sa.String(), nullable=True),
    sa.Column('LecturerDepartment', sa.String(), nullable=True),
    sa.Column('PracticianName', sa.String(), nullable=True),
    sa.Column('PracticianDepartment', sa.String(), nullable=True),
    sa.Column('course_work', sa.String(), nullable=True),
    sa.Column('practice_work', sa.String(), nullable=True),
    sa.Column('laboratory_work', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Group_id'], ['form_one.Group_id'], ),
    sa.ForeignKeyConstraint(['NumForm'], ['form_all.id'], ),
    sa.PrimaryKeyConstraint('NumForm', 'Group_id', 'id')
    )
    op.create_index(op.f('ix_form_two_id'), 'form_two', ['id'], unique=True)
    op.create_index(op.f('ix_form_two_timestamp'), 'form_two', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_two_timestamp'), table_name='form_two')
    op.drop_index(op.f('ix_form_two_id'), table_name='form_two')
    op.drop_table('form_two')
    op.drop_index(op.f('ix_form_one_timestamp'), table_name='form_one')
    op.drop_index(op.f('ix_form_one_Group_id'), table_name='form_one')
    op.drop_table('form_one')
    op.drop_table('group_stud')
    op.drop_index(op.f('ix_form_all_timestamp'), table_name='form_all')
    op.drop_index(op.f('ix_form_all_id'), table_name='form_all')
    op.drop_table('form_all')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_FullName'), table_name='user')
    op.drop_table('user')
    op.drop_table('profile')
    op.drop_table('direction')
    op.drop_table('department')
    op.drop_table('faculty')
    op.drop_table('degree')
    # ### end Alembic commands ###
