"""users table

Revision ID: dd4abce8770a
Revises: 
Create Date: 2020-04-28 16:03:12.039479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4abce8770a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('FullName', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('Phone', sa.String(length=12), nullable=True),
    sa.Column('access', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_FullName'), 'user', ['FullName'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Faculty_id', sa.Integer(), nullable=True),
    sa.Column('Faculty', sa.String(), nullable=True),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('Department', sa.String(), nullable=True),
    sa.Column('Degree_id', sa.Integer(), nullable=True),
    sa.Column('Degree', sa.String(), nullable=True),
    sa.Column('Year', sa.String(), nullable=True),
    sa.Column('Direction_id', sa.Integer(), nullable=True),
    sa.Column('Direction', sa.String(), nullable=True),
    sa.Column('Profile_id', sa.Integer(), nullable=True),
    sa.Column('Profile', sa.String(), nullable=True),
    sa.Column('Course', sa.Integer(), nullable=True),
    sa.Column('Group_id', sa.Integer(), nullable=True),
    sa.Column('NumStudents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_timestamp'), 'form', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_timestamp'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_FullName'), table_name='user')
    op.drop_table('user')
    op.drop_table('department')
    op.drop_table('faculty')
    # ### end Alembic commands ###
